//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AdmVed" type="{http://www.kith.no/xmlstds}CS"/&gt;
 *         &lt;element name="AdmMate" type="{http://www.kith.no/xmlstds}CS"/&gt;
 *         &lt;element name="AdmEtterSkjema" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="AdmSkjema" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "admVed",
    "admMate",
    "admEtterSkjema",
    "admSkjema"
})
@XmlRootElement(name = "AdministreringForskrivning")
public class AdministreringForskrivning
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "AdmVed", required = true)
    protected CS admVed;
    @XmlElement(name = "AdmMate", required = true)
    protected CS admMate;
    @XmlElement(name = "AdmEtterSkjema")
    protected Boolean admEtterSkjema;
    @XmlElement(name = "AdmSkjema")
    protected String admSkjema;

    /**
     * Gets the value of the admVed property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getAdmVed() {
        return admVed;
    }

    /**
     * Sets the value of the admVed property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setAdmVed(CS value) {
        this.admVed = value;
    }

    /**
     * Gets the value of the admMate property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getAdmMate() {
        return admMate;
    }

    /**
     * Sets the value of the admMate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setAdmMate(CS value) {
        this.admMate = value;
    }

    /**
     * Gets the value of the admEtterSkjema property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAdmEtterSkjema() {
        return admEtterSkjema;
    }

    /**
     * Sets the value of the admEtterSkjema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdmEtterSkjema(Boolean value) {
        this.admEtterSkjema = value;
    }

    /**
     * Gets the value of the admSkjema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmSkjema() {
        return admSkjema;
    }

    /**
     * Sets the value of the admSkjema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmSkjema(String value) {
        this.admSkjema = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CS theAdmVed;
            theAdmVed = this.getAdmVed();
            strategy.appendField(locator, this, "admVed", buffer, theAdmVed);
        }
        {
            CS theAdmMate;
            theAdmMate = this.getAdmMate();
            strategy.appendField(locator, this, "admMate", buffer, theAdmMate);
        }
        {
            Boolean theAdmEtterSkjema;
            theAdmEtterSkjema = this.getAdmEtterSkjema();
            strategy.appendField(locator, this, "admEtterSkjema", buffer, theAdmEtterSkjema);
        }
        {
            String theAdmSkjema;
            theAdmSkjema = this.getAdmSkjema();
            strategy.appendField(locator, this, "admSkjema", buffer, theAdmSkjema);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AdministreringForskrivning)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AdministreringForskrivning that = ((AdministreringForskrivning) object);
        {
            CS lhsAdmVed;
            lhsAdmVed = this.getAdmVed();
            CS rhsAdmVed;
            rhsAdmVed = that.getAdmVed();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "admVed", lhsAdmVed), LocatorUtils.property(thatLocator, "admVed", rhsAdmVed), lhsAdmVed, rhsAdmVed)) {
                return false;
            }
        }
        {
            CS lhsAdmMate;
            lhsAdmMate = this.getAdmMate();
            CS rhsAdmMate;
            rhsAdmMate = that.getAdmMate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "admMate", lhsAdmMate), LocatorUtils.property(thatLocator, "admMate", rhsAdmMate), lhsAdmMate, rhsAdmMate)) {
                return false;
            }
        }
        {
            Boolean lhsAdmEtterSkjema;
            lhsAdmEtterSkjema = this.getAdmEtterSkjema();
            Boolean rhsAdmEtterSkjema;
            rhsAdmEtterSkjema = that.getAdmEtterSkjema();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "admEtterSkjema", lhsAdmEtterSkjema), LocatorUtils.property(thatLocator, "admEtterSkjema", rhsAdmEtterSkjema), lhsAdmEtterSkjema, rhsAdmEtterSkjema)) {
                return false;
            }
        }
        {
            String lhsAdmSkjema;
            lhsAdmSkjema = this.getAdmSkjema();
            String rhsAdmSkjema;
            rhsAdmSkjema = that.getAdmSkjema();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "admSkjema", lhsAdmSkjema), LocatorUtils.property(thatLocator, "admSkjema", rhsAdmSkjema), lhsAdmSkjema, rhsAdmSkjema)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            CS theAdmVed;
            theAdmVed = this.getAdmVed();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "admVed", theAdmVed), currentHashCode, theAdmVed);
        }
        {
            CS theAdmMate;
            theAdmMate = this.getAdmMate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "admMate", theAdmMate), currentHashCode, theAdmMate);
        }
        {
            Boolean theAdmEtterSkjema;
            theAdmEtterSkjema = this.getAdmEtterSkjema();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "admEtterSkjema", theAdmEtterSkjema), currentHashCode, theAdmEtterSkjema);
        }
        {
            String theAdmSkjema;
            theAdmSkjema = this.getAdmSkjema();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "admSkjema", theAdmSkjema), currentHashCode, theAdmSkjema);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
