//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DoseresEtter" type="{http://www.kith.no/xmlstds}CS"/&gt;
 *         &lt;element name="Merknad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "doseresEtter",
    "merknad"
})
@XmlRootElement(name = "Doseringsregel")
public class Doseringsregel2
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "DoseresEtter", required = true)
    protected CS doseresEtter;
    @XmlElement(name = "Merknad")
    protected String merknad;

    /**
     * Gets the value of the doseresEtter property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getDoseresEtter() {
        return doseresEtter;
    }

    /**
     * Sets the value of the doseresEtter property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setDoseresEtter(CS value) {
        this.doseresEtter = value;
    }

    /**
     * Gets the value of the merknad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerknad() {
        return merknad;
    }

    /**
     * Sets the value of the merknad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerknad(String value) {
        this.merknad = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CS theDoseresEtter;
            theDoseresEtter = this.getDoseresEtter();
            strategy.appendField(locator, this, "doseresEtter", buffer, theDoseresEtter);
        }
        {
            String theMerknad;
            theMerknad = this.getMerknad();
            strategy.appendField(locator, this, "merknad", buffer, theMerknad);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Doseringsregel2)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Doseringsregel2 that = ((Doseringsregel2) object);
        {
            CS lhsDoseresEtter;
            lhsDoseresEtter = this.getDoseresEtter();
            CS rhsDoseresEtter;
            rhsDoseresEtter = that.getDoseresEtter();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "doseresEtter", lhsDoseresEtter), LocatorUtils.property(thatLocator, "doseresEtter", rhsDoseresEtter), lhsDoseresEtter, rhsDoseresEtter)) {
                return false;
            }
        }
        {
            String lhsMerknad;
            lhsMerknad = this.getMerknad();
            String rhsMerknad;
            rhsMerknad = that.getMerknad();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "merknad", lhsMerknad), LocatorUtils.property(thatLocator, "merknad", rhsMerknad), lhsMerknad, rhsMerknad)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            CS theDoseresEtter;
            theDoseresEtter = this.getDoseresEtter();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "doseresEtter", theDoseresEtter), currentHashCode, theDoseresEtter);
        }
        {
            String theMerknad;
            theMerknad = this.getMerknad();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "merknad", theMerknad), currentHashCode, theMerknad);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
