//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OppfHandelsvare" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
 *                 &lt;choice minOccurs="0"&gt;
 *                   &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}Brystprotese"/&gt;
 *                   &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}MedForbMatr"/&gt;
 *                   &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}Naringsmiddel"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oppfHandelsvare"
})
@XmlRootElement(name = "KatHandelsvare", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
public class KatHandelsvare
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "OppfHandelsvare", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    protected List<KatHandelsvare.OppfHandelsvare> oppfHandelsvare;

    /**
     * Gets the value of the oppfHandelsvare property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oppfHandelsvare property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOppfHandelsvare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KatHandelsvare.OppfHandelsvare }
     * 
     * 
     */
    public List<KatHandelsvare.OppfHandelsvare> getOppfHandelsvare() {
        if (oppfHandelsvare == null) {
            oppfHandelsvare = new ArrayList<KatHandelsvare.OppfHandelsvare>();
        }
        return this.oppfHandelsvare;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<KatHandelsvare.OppfHandelsvare> theOppfHandelsvare;
            theOppfHandelsvare = (((this.oppfHandelsvare!= null)&&(!this.oppfHandelsvare.isEmpty()))?this.getOppfHandelsvare():null);
            strategy.appendField(locator, this, "oppfHandelsvare", buffer, theOppfHandelsvare);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof KatHandelsvare)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final KatHandelsvare that = ((KatHandelsvare) object);
        {
            List<KatHandelsvare.OppfHandelsvare> lhsOppfHandelsvare;
            lhsOppfHandelsvare = (((this.oppfHandelsvare!= null)&&(!this.oppfHandelsvare.isEmpty()))?this.getOppfHandelsvare():null);
            List<KatHandelsvare.OppfHandelsvare> rhsOppfHandelsvare;
            rhsOppfHandelsvare = (((that.oppfHandelsvare!= null)&&(!that.oppfHandelsvare.isEmpty()))?that.getOppfHandelsvare():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "oppfHandelsvare", lhsOppfHandelsvare), LocatorUtils.property(thatLocator, "oppfHandelsvare", rhsOppfHandelsvare), lhsOppfHandelsvare, rhsOppfHandelsvare)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<KatHandelsvare.OppfHandelsvare> theOppfHandelsvare;
            theOppfHandelsvare = (((this.oppfHandelsvare!= null)&&(!this.oppfHandelsvare.isEmpty()))?this.getOppfHandelsvare():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oppfHandelsvare", theOppfHandelsvare), currentHashCode, theOppfHandelsvare);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
     *       &lt;choice minOccurs="0"&gt;
     *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}Brystprotese"/&gt;
     *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}MedForbMatr"/&gt;
     *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}Naringsmiddel"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brystprotese",
        "medForbMatr",
        "naringsmiddel"
    })
    public static class OppfHandelsvare
        extends TypeEnkeltoppforingFest
        implements Equals, HashCode, ToString
    {

        @XmlElement(name = "Brystprotese")
        protected TypeVare brystprotese;
        @XmlElement(name = "MedForbMatr")
        protected MedForbMatr medForbMatr;
        @XmlElement(name = "Naringsmiddel")
        protected Naringsmiddel naringsmiddel;

        /**
         * Gets the value of the brystprotese property.
         * 
         * @return
         *     possible object is
         *     {@link TypeVare }
         *     
         */
        public TypeVare getBrystprotese() {
            return brystprotese;
        }

        /**
         * Sets the value of the brystprotese property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeVare }
         *     
         */
        public void setBrystprotese(TypeVare value) {
            this.brystprotese = value;
        }

        /**
         * Gets the value of the medForbMatr property.
         * 
         * @return
         *     possible object is
         *     {@link MedForbMatr }
         *     
         */
        public MedForbMatr getMedForbMatr() {
            return medForbMatr;
        }

        /**
         * Sets the value of the medForbMatr property.
         * 
         * @param value
         *     allowed object is
         *     {@link MedForbMatr }
         *     
         */
        public void setMedForbMatr(MedForbMatr value) {
            this.medForbMatr = value;
        }

        /**
         * Gets the value of the naringsmiddel property.
         * 
         * @return
         *     possible object is
         *     {@link Naringsmiddel }
         *     
         */
        public Naringsmiddel getNaringsmiddel() {
            return naringsmiddel;
        }

        /**
         * Sets the value of the naringsmiddel property.
         * 
         * @param value
         *     allowed object is
         *     {@link Naringsmiddel }
         *     
         */
        public void setNaringsmiddel(Naringsmiddel value) {
            this.naringsmiddel = value;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            super.appendFields(locator, buffer, strategy);
            {
                TypeVare theBrystprotese;
                theBrystprotese = this.getBrystprotese();
                strategy.appendField(locator, this, "brystprotese", buffer, theBrystprotese);
            }
            {
                MedForbMatr theMedForbMatr;
                theMedForbMatr = this.getMedForbMatr();
                strategy.appendField(locator, this, "medForbMatr", buffer, theMedForbMatr);
            }
            {
                Naringsmiddel theNaringsmiddel;
                theNaringsmiddel = this.getNaringsmiddel();
                strategy.appendField(locator, this, "naringsmiddel", buffer, theNaringsmiddel);
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof KatHandelsvare.OppfHandelsvare)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            if (!super.equals(thisLocator, thatLocator, object, strategy)) {
                return false;
            }
            final KatHandelsvare.OppfHandelsvare that = ((KatHandelsvare.OppfHandelsvare) object);
            {
                TypeVare lhsBrystprotese;
                lhsBrystprotese = this.getBrystprotese();
                TypeVare rhsBrystprotese;
                rhsBrystprotese = that.getBrystprotese();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "brystprotese", lhsBrystprotese), LocatorUtils.property(thatLocator, "brystprotese", rhsBrystprotese), lhsBrystprotese, rhsBrystprotese)) {
                    return false;
                }
            }
            {
                MedForbMatr lhsMedForbMatr;
                lhsMedForbMatr = this.getMedForbMatr();
                MedForbMatr rhsMedForbMatr;
                rhsMedForbMatr = that.getMedForbMatr();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "medForbMatr", lhsMedForbMatr), LocatorUtils.property(thatLocator, "medForbMatr", rhsMedForbMatr), lhsMedForbMatr, rhsMedForbMatr)) {
                    return false;
                }
            }
            {
                Naringsmiddel lhsNaringsmiddel;
                lhsNaringsmiddel = this.getNaringsmiddel();
                Naringsmiddel rhsNaringsmiddel;
                rhsNaringsmiddel = that.getNaringsmiddel();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "naringsmiddel", lhsNaringsmiddel), LocatorUtils.property(thatLocator, "naringsmiddel", rhsNaringsmiddel), lhsNaringsmiddel, rhsNaringsmiddel)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = super.hashCode(locator, strategy);
            {
                TypeVare theBrystprotese;
                theBrystprotese = this.getBrystprotese();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "brystprotese", theBrystprotese), currentHashCode, theBrystprotese);
            }
            {
                MedForbMatr theMedForbMatr;
                theMedForbMatr = this.getMedForbMatr();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "medForbMatr", theMedForbMatr), currentHashCode, theMedForbMatr);
            }
            {
                Naringsmiddel theNaringsmiddel;
                theNaringsmiddel = this.getNaringsmiddel();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "naringsmiddel", theNaringsmiddel), currentHashCode, theNaringsmiddel);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
