//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OppfLegemiddelMerkevare" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
 *                 &lt;sequence minOccurs="0"&gt;
 *                   &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}LegemiddelMerkevare"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oppfLegemiddelMerkevare"
})
@XmlRootElement(name = "KatLegemiddelMerkevare", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
public class KatLegemiddelMerkevare
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "OppfLegemiddelMerkevare", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    protected List<KatLegemiddelMerkevare.OppfLegemiddelMerkevare> oppfLegemiddelMerkevare;

    /**
     * Gets the value of the oppfLegemiddelMerkevare property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oppfLegemiddelMerkevare property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOppfLegemiddelMerkevare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KatLegemiddelMerkevare.OppfLegemiddelMerkevare }
     * 
     * 
     */
    public List<KatLegemiddelMerkevare.OppfLegemiddelMerkevare> getOppfLegemiddelMerkevare() {
        if (oppfLegemiddelMerkevare == null) {
            oppfLegemiddelMerkevare = new ArrayList<KatLegemiddelMerkevare.OppfLegemiddelMerkevare>();
        }
        return this.oppfLegemiddelMerkevare;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<KatLegemiddelMerkevare.OppfLegemiddelMerkevare> theOppfLegemiddelMerkevare;
            theOppfLegemiddelMerkevare = (((this.oppfLegemiddelMerkevare!= null)&&(!this.oppfLegemiddelMerkevare.isEmpty()))?this.getOppfLegemiddelMerkevare():null);
            strategy.appendField(locator, this, "oppfLegemiddelMerkevare", buffer, theOppfLegemiddelMerkevare);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof KatLegemiddelMerkevare)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final KatLegemiddelMerkevare that = ((KatLegemiddelMerkevare) object);
        {
            List<KatLegemiddelMerkevare.OppfLegemiddelMerkevare> lhsOppfLegemiddelMerkevare;
            lhsOppfLegemiddelMerkevare = (((this.oppfLegemiddelMerkevare!= null)&&(!this.oppfLegemiddelMerkevare.isEmpty()))?this.getOppfLegemiddelMerkevare():null);
            List<KatLegemiddelMerkevare.OppfLegemiddelMerkevare> rhsOppfLegemiddelMerkevare;
            rhsOppfLegemiddelMerkevare = (((that.oppfLegemiddelMerkevare!= null)&&(!that.oppfLegemiddelMerkevare.isEmpty()))?that.getOppfLegemiddelMerkevare():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "oppfLegemiddelMerkevare", lhsOppfLegemiddelMerkevare), LocatorUtils.property(thatLocator, "oppfLegemiddelMerkevare", rhsOppfLegemiddelMerkevare), lhsOppfLegemiddelMerkevare, rhsOppfLegemiddelMerkevare)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<KatLegemiddelMerkevare.OppfLegemiddelMerkevare> theOppfLegemiddelMerkevare;
            theOppfLegemiddelMerkevare = (((this.oppfLegemiddelMerkevare!= null)&&(!this.oppfLegemiddelMerkevare.isEmpty()))?this.getOppfLegemiddelMerkevare():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oppfLegemiddelMerkevare", theOppfLegemiddelMerkevare), currentHashCode, theOppfLegemiddelMerkevare);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
     *       &lt;sequence minOccurs="0"&gt;
     *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}LegemiddelMerkevare"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "legemiddelMerkevare"
    })
    public static class OppfLegemiddelMerkevare
        extends TypeEnkeltoppforingFest
        implements Equals, HashCode, ToString
    {

        @XmlElement(name = "LegemiddelMerkevare")
        protected LegemiddelMerkevare legemiddelMerkevare;

        /**
         * Gets the value of the legemiddelMerkevare property.
         * 
         * @return
         *     possible object is
         *     {@link LegemiddelMerkevare }
         *     
         */
        public LegemiddelMerkevare getLegemiddelMerkevare() {
            return legemiddelMerkevare;
        }

        /**
         * Sets the value of the legemiddelMerkevare property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegemiddelMerkevare }
         *     
         */
        public void setLegemiddelMerkevare(LegemiddelMerkevare value) {
            this.legemiddelMerkevare = value;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            super.appendFields(locator, buffer, strategy);
            {
                LegemiddelMerkevare theLegemiddelMerkevare;
                theLegemiddelMerkevare = this.getLegemiddelMerkevare();
                strategy.appendField(locator, this, "legemiddelMerkevare", buffer, theLegemiddelMerkevare);
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof KatLegemiddelMerkevare.OppfLegemiddelMerkevare)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            if (!super.equals(thisLocator, thatLocator, object, strategy)) {
                return false;
            }
            final KatLegemiddelMerkevare.OppfLegemiddelMerkevare that = ((KatLegemiddelMerkevare.OppfLegemiddelMerkevare) object);
            {
                LegemiddelMerkevare lhsLegemiddelMerkevare;
                lhsLegemiddelMerkevare = this.getLegemiddelMerkevare();
                LegemiddelMerkevare rhsLegemiddelMerkevare;
                rhsLegemiddelMerkevare = that.getLegemiddelMerkevare();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "legemiddelMerkevare", lhsLegemiddelMerkevare), LocatorUtils.property(thatLocator, "legemiddelMerkevare", rhsLegemiddelMerkevare), lhsLegemiddelMerkevare, rhsLegemiddelMerkevare)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = super.hashCode(locator, strategy);
            {
                LegemiddelMerkevare theLegemiddelMerkevare;
                theLegemiddelMerkevare = this.getLegemiddelMerkevare();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "legemiddelMerkevare", theLegemiddelMerkevare), currentHashCode, theLegemiddelMerkevare);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
