//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OppfLegemiddelVirkestoff" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
 *                 &lt;sequence minOccurs="0"&gt;
 *                   &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}LegemiddelVirkestoff"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oppfLegemiddelVirkestoff"
})
@XmlRootElement(name = "KatLegemiddelVirkestoff", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
public class KatLegemiddelVirkestoff
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "OppfLegemiddelVirkestoff", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    protected List<KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff> oppfLegemiddelVirkestoff;

    /**
     * Gets the value of the oppfLegemiddelVirkestoff property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oppfLegemiddelVirkestoff property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOppfLegemiddelVirkestoff().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff }
     * 
     * 
     */
    public List<KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff> getOppfLegemiddelVirkestoff() {
        if (oppfLegemiddelVirkestoff == null) {
            oppfLegemiddelVirkestoff = new ArrayList<KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff>();
        }
        return this.oppfLegemiddelVirkestoff;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff> theOppfLegemiddelVirkestoff;
            theOppfLegemiddelVirkestoff = (((this.oppfLegemiddelVirkestoff!= null)&&(!this.oppfLegemiddelVirkestoff.isEmpty()))?this.getOppfLegemiddelVirkestoff():null);
            strategy.appendField(locator, this, "oppfLegemiddelVirkestoff", buffer, theOppfLegemiddelVirkestoff);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof KatLegemiddelVirkestoff)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final KatLegemiddelVirkestoff that = ((KatLegemiddelVirkestoff) object);
        {
            List<KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff> lhsOppfLegemiddelVirkestoff;
            lhsOppfLegemiddelVirkestoff = (((this.oppfLegemiddelVirkestoff!= null)&&(!this.oppfLegemiddelVirkestoff.isEmpty()))?this.getOppfLegemiddelVirkestoff():null);
            List<KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff> rhsOppfLegemiddelVirkestoff;
            rhsOppfLegemiddelVirkestoff = (((that.oppfLegemiddelVirkestoff!= null)&&(!that.oppfLegemiddelVirkestoff.isEmpty()))?that.getOppfLegemiddelVirkestoff():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "oppfLegemiddelVirkestoff", lhsOppfLegemiddelVirkestoff), LocatorUtils.property(thatLocator, "oppfLegemiddelVirkestoff", rhsOppfLegemiddelVirkestoff), lhsOppfLegemiddelVirkestoff, rhsOppfLegemiddelVirkestoff)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff> theOppfLegemiddelVirkestoff;
            theOppfLegemiddelVirkestoff = (((this.oppfLegemiddelVirkestoff!= null)&&(!this.oppfLegemiddelVirkestoff.isEmpty()))?this.getOppfLegemiddelVirkestoff():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oppfLegemiddelVirkestoff", theOppfLegemiddelVirkestoff), currentHashCode, theOppfLegemiddelVirkestoff);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
     *       &lt;sequence minOccurs="0"&gt;
     *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}LegemiddelVirkestoff"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "legemiddelVirkestoff"
    })
    public static class OppfLegemiddelVirkestoff
        extends TypeEnkeltoppforingFest
        implements Equals, HashCode, ToString
    {

        @XmlElement(name = "LegemiddelVirkestoff")
        protected LegemiddelVirkestoff legemiddelVirkestoff;

        /**
         * Gets the value of the legemiddelVirkestoff property.
         * 
         * @return
         *     possible object is
         *     {@link LegemiddelVirkestoff }
         *     
         */
        public LegemiddelVirkestoff getLegemiddelVirkestoff() {
            return legemiddelVirkestoff;
        }

        /**
         * Sets the value of the legemiddelVirkestoff property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegemiddelVirkestoff }
         *     
         */
        public void setLegemiddelVirkestoff(LegemiddelVirkestoff value) {
            this.legemiddelVirkestoff = value;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            super.appendFields(locator, buffer, strategy);
            {
                LegemiddelVirkestoff theLegemiddelVirkestoff;
                theLegemiddelVirkestoff = this.getLegemiddelVirkestoff();
                strategy.appendField(locator, this, "legemiddelVirkestoff", buffer, theLegemiddelVirkestoff);
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            if (!super.equals(thisLocator, thatLocator, object, strategy)) {
                return false;
            }
            final KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff that = ((KatLegemiddelVirkestoff.OppfLegemiddelVirkestoff) object);
            {
                LegemiddelVirkestoff lhsLegemiddelVirkestoff;
                lhsLegemiddelVirkestoff = this.getLegemiddelVirkestoff();
                LegemiddelVirkestoff rhsLegemiddelVirkestoff;
                rhsLegemiddelVirkestoff = that.getLegemiddelVirkestoff();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "legemiddelVirkestoff", lhsLegemiddelVirkestoff), LocatorUtils.property(thatLocator, "legemiddelVirkestoff", rhsLegemiddelVirkestoff), lhsLegemiddelVirkestoff, rhsLegemiddelVirkestoff)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = super.hashCode(locator, strategy);
            {
                LegemiddelVirkestoff theLegemiddelVirkestoff;
                theLegemiddelVirkestoff = this.getLegemiddelVirkestoff();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "legemiddelVirkestoff", theLegemiddelVirkestoff), currentHashCode, theLegemiddelVirkestoff);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
