//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OppfRefusjon" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
 *                 &lt;sequence minOccurs="0"&gt;
 *                   &lt;element ref="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}Refusjonshjemmel"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oppfRefusjon"
})
@XmlRootElement(name = "KatRefusjon", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
public class KatRefusjon
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "OppfRefusjon", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    protected List<KatRefusjon.OppfRefusjon> oppfRefusjon;

    /**
     * Gets the value of the oppfRefusjon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oppfRefusjon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOppfRefusjon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KatRefusjon.OppfRefusjon }
     * 
     * 
     */
    public List<KatRefusjon.OppfRefusjon> getOppfRefusjon() {
        if (oppfRefusjon == null) {
            oppfRefusjon = new ArrayList<KatRefusjon.OppfRefusjon>();
        }
        return this.oppfRefusjon;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<KatRefusjon.OppfRefusjon> theOppfRefusjon;
            theOppfRefusjon = (((this.oppfRefusjon!= null)&&(!this.oppfRefusjon.isEmpty()))?this.getOppfRefusjon():null);
            strategy.appendField(locator, this, "oppfRefusjon", buffer, theOppfRefusjon);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof KatRefusjon)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final KatRefusjon that = ((KatRefusjon) object);
        {
            List<KatRefusjon.OppfRefusjon> lhsOppfRefusjon;
            lhsOppfRefusjon = (((this.oppfRefusjon!= null)&&(!this.oppfRefusjon.isEmpty()))?this.getOppfRefusjon():null);
            List<KatRefusjon.OppfRefusjon> rhsOppfRefusjon;
            rhsOppfRefusjon = (((that.oppfRefusjon!= null)&&(!that.oppfRefusjon.isEmpty()))?that.getOppfRefusjon():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "oppfRefusjon", lhsOppfRefusjon), LocatorUtils.property(thatLocator, "oppfRefusjon", rhsOppfRefusjon), lhsOppfRefusjon, rhsOppfRefusjon)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<KatRefusjon.OppfRefusjon> theOppfRefusjon;
            theOppfRefusjon = (((this.oppfRefusjon!= null)&&(!this.oppfRefusjon.isEmpty()))?this.getOppfRefusjon():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oppfRefusjon", theOppfRefusjon), currentHashCode, theOppfRefusjon);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
     *       &lt;sequence minOccurs="0"&gt;
     *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}Refusjonshjemmel"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refusjonshjemmel"
    })
    public static class OppfRefusjon
        extends TypeEnkeltoppforingFest
        implements Equals, HashCode, ToString
    {

        @XmlElement(name = "Refusjonshjemmel", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
        protected Refusjonshjemmel refusjonshjemmel;

        /**
         * Gets the value of the refusjonshjemmel property.
         * 
         * @return
         *     possible object is
         *     {@link Refusjonshjemmel }
         *     
         */
        public Refusjonshjemmel getRefusjonshjemmel() {
            return refusjonshjemmel;
        }

        /**
         * Sets the value of the refusjonshjemmel property.
         * 
         * @param value
         *     allowed object is
         *     {@link Refusjonshjemmel }
         *     
         */
        public void setRefusjonshjemmel(Refusjonshjemmel value) {
            this.refusjonshjemmel = value;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            super.appendFields(locator, buffer, strategy);
            {
                Refusjonshjemmel theRefusjonshjemmel;
                theRefusjonshjemmel = this.getRefusjonshjemmel();
                strategy.appendField(locator, this, "refusjonshjemmel", buffer, theRefusjonshjemmel);
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof KatRefusjon.OppfRefusjon)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            if (!super.equals(thisLocator, thatLocator, object, strategy)) {
                return false;
            }
            final KatRefusjon.OppfRefusjon that = ((KatRefusjon.OppfRefusjon) object);
            {
                Refusjonshjemmel lhsRefusjonshjemmel;
                lhsRefusjonshjemmel = this.getRefusjonshjemmel();
                Refusjonshjemmel rhsRefusjonshjemmel;
                rhsRefusjonshjemmel = that.getRefusjonshjemmel();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "refusjonshjemmel", lhsRefusjonshjemmel), LocatorUtils.property(thatLocator, "refusjonshjemmel", rhsRefusjonshjemmel), lhsRefusjonshjemmel, rhsRefusjonshjemmel)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = super.hashCode(locator, strategy);
            {
                Refusjonshjemmel theRefusjonshjemmel;
                theRefusjonshjemmel = this.getRefusjonshjemmel();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refusjonshjemmel", theRefusjonshjemmel), currentHashCode, theRefusjonshjemmel);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
