//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OppfVarselSlv" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
 *                 &lt;sequence minOccurs="0"&gt;
 *                   &lt;element ref="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}VarselSlv"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oppfVarselSlv"
})
@XmlRootElement(name = "KatVarselSlv", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
public class KatVarselSlv
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "OppfVarselSlv", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    protected List<KatVarselSlv.OppfVarselSlv> oppfVarselSlv;

    /**
     * Gets the value of the oppfVarselSlv property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oppfVarselSlv property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOppfVarselSlv().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KatVarselSlv.OppfVarselSlv }
     * 
     * 
     */
    public List<KatVarselSlv.OppfVarselSlv> getOppfVarselSlv() {
        if (oppfVarselSlv == null) {
            oppfVarselSlv = new ArrayList<KatVarselSlv.OppfVarselSlv>();
        }
        return this.oppfVarselSlv;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<KatVarselSlv.OppfVarselSlv> theOppfVarselSlv;
            theOppfVarselSlv = (((this.oppfVarselSlv!= null)&&(!this.oppfVarselSlv.isEmpty()))?this.getOppfVarselSlv():null);
            strategy.appendField(locator, this, "oppfVarselSlv", buffer, theOppfVarselSlv);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof KatVarselSlv)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final KatVarselSlv that = ((KatVarselSlv) object);
        {
            List<KatVarselSlv.OppfVarselSlv> lhsOppfVarselSlv;
            lhsOppfVarselSlv = (((this.oppfVarselSlv!= null)&&(!this.oppfVarselSlv.isEmpty()))?this.getOppfVarselSlv():null);
            List<KatVarselSlv.OppfVarselSlv> rhsOppfVarselSlv;
            rhsOppfVarselSlv = (((that.oppfVarselSlv!= null)&&(!that.oppfVarselSlv.isEmpty()))?that.getOppfVarselSlv():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "oppfVarselSlv", lhsOppfVarselSlv), LocatorUtils.property(thatLocator, "oppfVarselSlv", rhsOppfVarselSlv), lhsOppfVarselSlv, rhsOppfVarselSlv)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<KatVarselSlv.OppfVarselSlv> theOppfVarselSlv;
            theOppfVarselSlv = (((this.oppfVarselSlv!= null)&&(!this.oppfVarselSlv.isEmpty()))?this.getOppfVarselSlv():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oppfVarselSlv", theOppfVarselSlv), currentHashCode, theOppfVarselSlv);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}typeEnkeltoppforingFest"&gt;
     *       &lt;sequence minOccurs="0"&gt;
     *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}VarselSlv"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "varselSlv"
    })
    public static class OppfVarselSlv
        extends TypeEnkeltoppforingFest
        implements Equals, HashCode, ToString
    {

        @XmlElement(name = "VarselSlv", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
        protected VarselSlv varselSlv;

        /**
         * Gets the value of the varselSlv property.
         * 
         * @return
         *     possible object is
         *     {@link VarselSlv }
         *     
         */
        public VarselSlv getVarselSlv() {
            return varselSlv;
        }

        /**
         * Sets the value of the varselSlv property.
         * 
         * @param value
         *     allowed object is
         *     {@link VarselSlv }
         *     
         */
        public void setVarselSlv(VarselSlv value) {
            this.varselSlv = value;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            super.appendFields(locator, buffer, strategy);
            {
                VarselSlv theVarselSlv;
                theVarselSlv = this.getVarselSlv();
                strategy.appendField(locator, this, "varselSlv", buffer, theVarselSlv);
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof KatVarselSlv.OppfVarselSlv)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            if (!super.equals(thisLocator, thatLocator, object, strategy)) {
                return false;
            }
            final KatVarselSlv.OppfVarselSlv that = ((KatVarselSlv.OppfVarselSlv) object);
            {
                VarselSlv lhsVarselSlv;
                lhsVarselSlv = this.getVarselSlv();
                VarselSlv rhsVarselSlv;
                rhsVarselSlv = that.getVarselSlv();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "varselSlv", lhsVarselSlv), LocatorUtils.property(thatLocator, "varselSlv", rhsVarselSlv), lhsVarselSlv, rhsVarselSlv)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = super.hashCode(locator, strategy);
            {
                VarselSlv theVarselSlv;
                theVarselSlv = this.getVarselSlv();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "varselSlv", theVarselSlv), currentHashCode, theVarselSlv);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
