//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}typeVare"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}BestanddelMatr" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bestanddelMatr"
})
@XmlRootElement(name = "MedForbMatr")
public class MedForbMatr
    extends TypeVare
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "BestanddelMatr")
    protected List<BestanddelMatr> bestanddelMatr;

    /**
     * Gets the value of the bestanddelMatr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bestanddelMatr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBestanddelMatr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BestanddelMatr }
     * 
     * 
     */
    public List<BestanddelMatr> getBestanddelMatr() {
        if (bestanddelMatr == null) {
            bestanddelMatr = new ArrayList<BestanddelMatr>();
        }
        return this.bestanddelMatr;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<BestanddelMatr> theBestanddelMatr;
            theBestanddelMatr = (((this.bestanddelMatr!= null)&&(!this.bestanddelMatr.isEmpty()))?this.getBestanddelMatr():null);
            strategy.appendField(locator, this, "bestanddelMatr", buffer, theBestanddelMatr);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof MedForbMatr)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final MedForbMatr that = ((MedForbMatr) object);
        {
            List<BestanddelMatr> lhsBestanddelMatr;
            lhsBestanddelMatr = (((this.bestanddelMatr!= null)&&(!this.bestanddelMatr.isEmpty()))?this.getBestanddelMatr():null);
            List<BestanddelMatr> rhsBestanddelMatr;
            rhsBestanddelMatr = (((that.bestanddelMatr!= null)&&(!that.bestanddelMatr.isEmpty()))?that.getBestanddelMatr():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "bestanddelMatr", lhsBestanddelMatr), LocatorUtils.property(thatLocator, "bestanddelMatr", rhsBestanddelMatr), lhsBestanddelMatr, rhsBestanddelMatr)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<BestanddelMatr> theBestanddelMatr;
            theBestanddelMatr = (((this.bestanddelMatr!= null)&&(!this.bestanddelMatr.isEmpty()))?this.getBestanddelMatr():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bestanddelMatr", theBestanddelMatr), currentHashCode, theBestanddelMatr);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
