//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package no.uia.ehealth.workflow;
