//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Varenavn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Pakningsstr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EnhetPakning" type="{http://www.kith.no/xmlstds}CV"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "varenavn",
    "pakningsstr",
    "enhetPakning"
})
@XmlRootElement(name = "PakningsinfoResept")
public class PakningsinfoResept
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "Varenavn", required = true)
    protected String varenavn;
    @XmlElement(name = "Pakningsstr", required = true)
    protected String pakningsstr;
    @XmlElement(name = "EnhetPakning", required = true)
    protected CV enhetPakning;

    /**
     * Gets the value of the varenavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarenavn() {
        return varenavn;
    }

    /**
     * Sets the value of the varenavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarenavn(String value) {
        this.varenavn = value;
    }

    /**
     * Gets the value of the pakningsstr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPakningsstr() {
        return pakningsstr;
    }

    /**
     * Sets the value of the pakningsstr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPakningsstr(String value) {
        this.pakningsstr = value;
    }

    /**
     * Gets the value of the enhetPakning property.
     * 
     * @return
     *     possible object is
     *     {@link CV }
     *     
     */
    public CV getEnhetPakning() {
        return enhetPakning;
    }

    /**
     * Sets the value of the enhetPakning property.
     * 
     * @param value
     *     allowed object is
     *     {@link CV }
     *     
     */
    public void setEnhetPakning(CV value) {
        this.enhetPakning = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theVarenavn;
            theVarenavn = this.getVarenavn();
            strategy.appendField(locator, this, "varenavn", buffer, theVarenavn);
        }
        {
            String thePakningsstr;
            thePakningsstr = this.getPakningsstr();
            strategy.appendField(locator, this, "pakningsstr", buffer, thePakningsstr);
        }
        {
            CV theEnhetPakning;
            theEnhetPakning = this.getEnhetPakning();
            strategy.appendField(locator, this, "enhetPakning", buffer, theEnhetPakning);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PakningsinfoResept)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PakningsinfoResept that = ((PakningsinfoResept) object);
        {
            String lhsVarenavn;
            lhsVarenavn = this.getVarenavn();
            String rhsVarenavn;
            rhsVarenavn = that.getVarenavn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "varenavn", lhsVarenavn), LocatorUtils.property(thatLocator, "varenavn", rhsVarenavn), lhsVarenavn, rhsVarenavn)) {
                return false;
            }
        }
        {
            String lhsPakningsstr;
            lhsPakningsstr = this.getPakningsstr();
            String rhsPakningsstr;
            rhsPakningsstr = that.getPakningsstr();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pakningsstr", lhsPakningsstr), LocatorUtils.property(thatLocator, "pakningsstr", rhsPakningsstr), lhsPakningsstr, rhsPakningsstr)) {
                return false;
            }
        }
        {
            CV lhsEnhetPakning;
            lhsEnhetPakning = this.getEnhetPakning();
            CV rhsEnhetPakning;
            rhsEnhetPakning = that.getEnhetPakning();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "enhetPakning", lhsEnhetPakning), LocatorUtils.property(thatLocator, "enhetPakning", rhsEnhetPakning), lhsEnhetPakning, rhsEnhetPakning)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theVarenavn;
            theVarenavn = this.getVarenavn();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "varenavn", theVarenavn), currentHashCode, theVarenavn);
        }
        {
            String thePakningsstr;
            thePakningsstr = this.getPakningsstr();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "pakningsstr", thePakningsstr), currentHashCode, thePakningsstr);
        }
        {
            CV theEnhetPakning;
            theEnhetPakning = this.getEnhetPakning();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "enhetPakning", theEnhetPakning), currentHashCode, theEnhetPakning);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
