//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RefByttegruppe" type="{http://www.w3.org/2001/XMLSchema}IDREF"/&gt;
 *         &lt;element name="GyldigFraDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="GyldigTilDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refByttegruppe",
    "gyldigFraDato",
    "gyldigTilDato"
})
@XmlRootElement(name = "PakningByttegruppe")
public class PakningByttegruppe
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "RefByttegruppe", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object refByttegruppe;
    @XmlElement(name = "GyldigFraDato")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gyldigFraDato;
    @XmlElement(name = "GyldigTilDato")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gyldigTilDato;

    /**
     * Gets the value of the refByttegruppe property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRefByttegruppe() {
        return refByttegruppe;
    }

    /**
     * Sets the value of the refByttegruppe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRefByttegruppe(Object value) {
        this.refByttegruppe = value;
    }

    /**
     * Gets the value of the gyldigFraDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGyldigFraDato() {
        return gyldigFraDato;
    }

    /**
     * Sets the value of the gyldigFraDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGyldigFraDato(XMLGregorianCalendar value) {
        this.gyldigFraDato = value;
    }

    /**
     * Gets the value of the gyldigTilDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGyldigTilDato() {
        return gyldigTilDato;
    }

    /**
     * Sets the value of the gyldigTilDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGyldigTilDato(XMLGregorianCalendar value) {
        this.gyldigTilDato = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Object theRefByttegruppe;
            theRefByttegruppe = this.getRefByttegruppe();
            strategy.appendField(locator, this, "refByttegruppe", buffer, theRefByttegruppe);
        }
        {
            XMLGregorianCalendar theGyldigFraDato;
            theGyldigFraDato = this.getGyldigFraDato();
            strategy.appendField(locator, this, "gyldigFraDato", buffer, theGyldigFraDato);
        }
        {
            XMLGregorianCalendar theGyldigTilDato;
            theGyldigTilDato = this.getGyldigTilDato();
            strategy.appendField(locator, this, "gyldigTilDato", buffer, theGyldigTilDato);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PakningByttegruppe)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PakningByttegruppe that = ((PakningByttegruppe) object);
        {
            Object lhsRefByttegruppe;
            lhsRefByttegruppe = this.getRefByttegruppe();
            Object rhsRefByttegruppe;
            rhsRefByttegruppe = that.getRefByttegruppe();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "refByttegruppe", lhsRefByttegruppe), LocatorUtils.property(thatLocator, "refByttegruppe", rhsRefByttegruppe), lhsRefByttegruppe, rhsRefByttegruppe)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsGyldigFraDato;
            lhsGyldigFraDato = this.getGyldigFraDato();
            XMLGregorianCalendar rhsGyldigFraDato;
            rhsGyldigFraDato = that.getGyldigFraDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "gyldigFraDato", lhsGyldigFraDato), LocatorUtils.property(thatLocator, "gyldigFraDato", rhsGyldigFraDato), lhsGyldigFraDato, rhsGyldigFraDato)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsGyldigTilDato;
            lhsGyldigTilDato = this.getGyldigTilDato();
            XMLGregorianCalendar rhsGyldigTilDato;
            rhsGyldigTilDato = that.getGyldigTilDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "gyldigTilDato", lhsGyldigTilDato), LocatorUtils.property(thatLocator, "gyldigTilDato", rhsGyldigTilDato), lhsGyldigTilDato, rhsGyldigTilDato)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Object theRefByttegruppe;
            theRefByttegruppe = this.getRefByttegruppe();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refByttegruppe", theRefByttegruppe), currentHashCode, theRefByttegruppe);
        }
        {
            XMLGregorianCalendar theGyldigFraDato;
            theGyldigFraDato = this.getGyldigFraDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "gyldigFraDato", theGyldigFraDato), currentHashCode, theGyldigFraDato);
        }
        {
            XMLGregorianCalendar theGyldigTilDato;
            theGyldigTilDato = this.getGyldigTilDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "gyldigTilDato", theGyldigTilDato), currentHashCode, theGyldigTilDato);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
