//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Pakningstype" type="{http://www.kith.no/xmlstds}CV"/&gt;
 *         &lt;element name="Mengde" type="{http://www.kith.no/xmlstds}PQ"/&gt;
 *         &lt;element name="Antall" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pakningstype",
    "mengde",
    "antall"
})
@XmlRootElement(name = "Pakningskomponent")
public class Pakningskomponent
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "Pakningstype", required = true)
    protected CV pakningstype;
    @XmlElement(name = "Mengde", required = true)
    protected PQ mengde;
    @XmlElement(name = "Antall")
    protected Integer antall;

    /**
     * Gets the value of the pakningstype property.
     * 
     * @return
     *     possible object is
     *     {@link CV }
     *     
     */
    public CV getPakningstype() {
        return pakningstype;
    }

    /**
     * Sets the value of the pakningstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CV }
     *     
     */
    public void setPakningstype(CV value) {
        this.pakningstype = value;
    }

    /**
     * Gets the value of the mengde property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getMengde() {
        return mengde;
    }

    /**
     * Sets the value of the mengde property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setMengde(PQ value) {
        this.mengde = value;
    }

    /**
     * Gets the value of the antall property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAntall() {
        return antall;
    }

    /**
     * Sets the value of the antall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAntall(Integer value) {
        this.antall = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CV thePakningstype;
            thePakningstype = this.getPakningstype();
            strategy.appendField(locator, this, "pakningstype", buffer, thePakningstype);
        }
        {
            PQ theMengde;
            theMengde = this.getMengde();
            strategy.appendField(locator, this, "mengde", buffer, theMengde);
        }
        {
            Integer theAntall;
            theAntall = this.getAntall();
            strategy.appendField(locator, this, "antall", buffer, theAntall);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Pakningskomponent)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Pakningskomponent that = ((Pakningskomponent) object);
        {
            CV lhsPakningstype;
            lhsPakningstype = this.getPakningstype();
            CV rhsPakningstype;
            rhsPakningstype = that.getPakningstype();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pakningstype", lhsPakningstype), LocatorUtils.property(thatLocator, "pakningstype", rhsPakningstype), lhsPakningstype, rhsPakningstype)) {
                return false;
            }
        }
        {
            PQ lhsMengde;
            lhsMengde = this.getMengde();
            PQ rhsMengde;
            rhsMengde = that.getMengde();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "mengde", lhsMengde), LocatorUtils.property(thatLocator, "mengde", rhsMengde), lhsMengde, rhsMengde)) {
                return false;
            }
        }
        {
            Integer lhsAntall;
            lhsAntall = this.getAntall();
            Integer rhsAntall;
            rhsAntall = that.getAntall();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "antall", lhsAntall), LocatorUtils.property(thatLocator, "antall", rhsAntall), lhsAntall, rhsAntall)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            CV thePakningstype;
            thePakningstype = this.getPakningstype();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "pakningstype", thePakningstype), currentHashCode, thePakningstype);
        }
        {
            PQ theMengde;
            theMengde = this.getMengde();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "mengde", theMengde), currentHashCode, theMengde);
        }
        {
            Integer theAntall;
            theAntall = this.getAntall();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "antall", theAntall), currentHashCode, theAntall);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
