//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Refusjonskode" type="{http://www.kith.no/xmlstds}CV"/&gt;
 *         &lt;element name="Underterm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GyldigFraDato" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ForskrivesTilDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="UtleveresTilDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/m30/2014-12-01}Refusjonsvilkar" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refusjonskode",
    "underterm",
    "gyldigFraDato",
    "forskrivesTilDato",
    "utleveresTilDato",
    "refusjonsvilkar"
})
@XmlRootElement(name = "Refusjonskode", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
public class Refusjonskode
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "Refusjonskode", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01", required = true)
    protected CV refusjonskode;
    @XmlElement(name = "Underterm", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    protected String underterm;
    @XmlElement(name = "GyldigFraDato", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gyldigFraDato;
    @XmlElement(name = "ForskrivesTilDato", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar forskrivesTilDato;
    @XmlElement(name = "UtleveresTilDato", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar utleveresTilDato;
    @XmlElement(name = "Refusjonsvilkar", namespace = "http://www.kith.no/xmlstds/eresept/m30/2014-12-01")
    protected List<Refusjonsvilkar> refusjonsvilkar;

    /**
     * Gets the value of the refusjonskode property.
     * 
     * @return
     *     possible object is
     *     {@link CV }
     *     
     */
    public CV getRefusjonskode() {
        return refusjonskode;
    }

    /**
     * Sets the value of the refusjonskode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CV }
     *     
     */
    public void setRefusjonskode(CV value) {
        this.refusjonskode = value;
    }

    /**
     * Gets the value of the underterm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderterm() {
        return underterm;
    }

    /**
     * Sets the value of the underterm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderterm(String value) {
        this.underterm = value;
    }

    /**
     * Gets the value of the gyldigFraDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGyldigFraDato() {
        return gyldigFraDato;
    }

    /**
     * Sets the value of the gyldigFraDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGyldigFraDato(XMLGregorianCalendar value) {
        this.gyldigFraDato = value;
    }

    /**
     * Gets the value of the forskrivesTilDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getForskrivesTilDato() {
        return forskrivesTilDato;
    }

    /**
     * Sets the value of the forskrivesTilDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setForskrivesTilDato(XMLGregorianCalendar value) {
        this.forskrivesTilDato = value;
    }

    /**
     * Gets the value of the utleveresTilDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUtleveresTilDato() {
        return utleveresTilDato;
    }

    /**
     * Sets the value of the utleveresTilDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUtleveresTilDato(XMLGregorianCalendar value) {
        this.utleveresTilDato = value;
    }

    /**
     * Gets the value of the refusjonsvilkar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refusjonsvilkar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefusjonsvilkar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Refusjonsvilkar }
     * 
     * 
     */
    public List<Refusjonsvilkar> getRefusjonsvilkar() {
        if (refusjonsvilkar == null) {
            refusjonsvilkar = new ArrayList<Refusjonsvilkar>();
        }
        return this.refusjonsvilkar;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CV theRefusjonskode;
            theRefusjonskode = this.getRefusjonskode();
            strategy.appendField(locator, this, "refusjonskode", buffer, theRefusjonskode);
        }
        {
            String theUnderterm;
            theUnderterm = this.getUnderterm();
            strategy.appendField(locator, this, "underterm", buffer, theUnderterm);
        }
        {
            XMLGregorianCalendar theGyldigFraDato;
            theGyldigFraDato = this.getGyldigFraDato();
            strategy.appendField(locator, this, "gyldigFraDato", buffer, theGyldigFraDato);
        }
        {
            XMLGregorianCalendar theForskrivesTilDato;
            theForskrivesTilDato = this.getForskrivesTilDato();
            strategy.appendField(locator, this, "forskrivesTilDato", buffer, theForskrivesTilDato);
        }
        {
            XMLGregorianCalendar theUtleveresTilDato;
            theUtleveresTilDato = this.getUtleveresTilDato();
            strategy.appendField(locator, this, "utleveresTilDato", buffer, theUtleveresTilDato);
        }
        {
            List<Refusjonsvilkar> theRefusjonsvilkar;
            theRefusjonsvilkar = (((this.refusjonsvilkar!= null)&&(!this.refusjonsvilkar.isEmpty()))?this.getRefusjonsvilkar():null);
            strategy.appendField(locator, this, "refusjonsvilkar", buffer, theRefusjonsvilkar);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Refusjonskode)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Refusjonskode that = ((Refusjonskode) object);
        {
            CV lhsRefusjonskode;
            lhsRefusjonskode = this.getRefusjonskode();
            CV rhsRefusjonskode;
            rhsRefusjonskode = that.getRefusjonskode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "refusjonskode", lhsRefusjonskode), LocatorUtils.property(thatLocator, "refusjonskode", rhsRefusjonskode), lhsRefusjonskode, rhsRefusjonskode)) {
                return false;
            }
        }
        {
            String lhsUnderterm;
            lhsUnderterm = this.getUnderterm();
            String rhsUnderterm;
            rhsUnderterm = that.getUnderterm();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "underterm", lhsUnderterm), LocatorUtils.property(thatLocator, "underterm", rhsUnderterm), lhsUnderterm, rhsUnderterm)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsGyldigFraDato;
            lhsGyldigFraDato = this.getGyldigFraDato();
            XMLGregorianCalendar rhsGyldigFraDato;
            rhsGyldigFraDato = that.getGyldigFraDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "gyldigFraDato", lhsGyldigFraDato), LocatorUtils.property(thatLocator, "gyldigFraDato", rhsGyldigFraDato), lhsGyldigFraDato, rhsGyldigFraDato)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsForskrivesTilDato;
            lhsForskrivesTilDato = this.getForskrivesTilDato();
            XMLGregorianCalendar rhsForskrivesTilDato;
            rhsForskrivesTilDato = that.getForskrivesTilDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "forskrivesTilDato", lhsForskrivesTilDato), LocatorUtils.property(thatLocator, "forskrivesTilDato", rhsForskrivesTilDato), lhsForskrivesTilDato, rhsForskrivesTilDato)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsUtleveresTilDato;
            lhsUtleveresTilDato = this.getUtleveresTilDato();
            XMLGregorianCalendar rhsUtleveresTilDato;
            rhsUtleveresTilDato = that.getUtleveresTilDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "utleveresTilDato", lhsUtleveresTilDato), LocatorUtils.property(thatLocator, "utleveresTilDato", rhsUtleveresTilDato), lhsUtleveresTilDato, rhsUtleveresTilDato)) {
                return false;
            }
        }
        {
            List<Refusjonsvilkar> lhsRefusjonsvilkar;
            lhsRefusjonsvilkar = (((this.refusjonsvilkar!= null)&&(!this.refusjonsvilkar.isEmpty()))?this.getRefusjonsvilkar():null);
            List<Refusjonsvilkar> rhsRefusjonsvilkar;
            rhsRefusjonsvilkar = (((that.refusjonsvilkar!= null)&&(!that.refusjonsvilkar.isEmpty()))?that.getRefusjonsvilkar():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "refusjonsvilkar", lhsRefusjonsvilkar), LocatorUtils.property(thatLocator, "refusjonsvilkar", rhsRefusjonsvilkar), lhsRefusjonsvilkar, rhsRefusjonsvilkar)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            CV theRefusjonskode;
            theRefusjonskode = this.getRefusjonskode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refusjonskode", theRefusjonskode), currentHashCode, theRefusjonskode);
        }
        {
            String theUnderterm;
            theUnderterm = this.getUnderterm();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "underterm", theUnderterm), currentHashCode, theUnderterm);
        }
        {
            XMLGregorianCalendar theGyldigFraDato;
            theGyldigFraDato = this.getGyldigFraDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "gyldigFraDato", theGyldigFraDato), currentHashCode, theGyldigFraDato);
        }
        {
            XMLGregorianCalendar theForskrivesTilDato;
            theForskrivesTilDato = this.getForskrivesTilDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "forskrivesTilDato", theForskrivesTilDato), currentHashCode, theForskrivesTilDato);
        }
        {
            XMLGregorianCalendar theUtleveresTilDato;
            theUtleveresTilDato = this.getUtleveresTilDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "utleveresTilDato", theUtleveresTilDato), currentHashCode, theUtleveresTilDato);
        }
        {
            List<Refusjonsvilkar> theRefusjonsvilkar;
            theRefusjonsvilkar = (((this.refusjonsvilkar!= null)&&(!this.refusjonsvilkar.isEmpty()))?this.getRefusjonsvilkar():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refusjonsvilkar", theRefusjonsvilkar), currentHashCode, theRefusjonsvilkar);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
