//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RefRefusjonsgruppe" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded"/&gt;
 *         &lt;element name="GyldigFraDato" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ForskrivesTilDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="UtleveresTilDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refRefusjonsgruppe",
    "gyldigFraDato",
    "forskrivesTilDato",
    "utleveresTilDato"
})
@XmlRootElement(name = "Refusjon")
public class Refusjon
    implements Equals, HashCode, ToString
{

    @XmlElementRef(name = "RefRefusjonsgruppe", namespace = "http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01", type = JAXBElement.class)
    protected List<JAXBElement<Object>> refRefusjonsgruppe;
    @XmlElement(name = "GyldigFraDato", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gyldigFraDato;
    @XmlElement(name = "ForskrivesTilDato")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar forskrivesTilDato;
    @XmlElement(name = "UtleveresTilDato")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar utleveresTilDato;

    /**
     * Gets the value of the refRefusjonsgruppe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refRefusjonsgruppe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefRefusjonsgruppe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getRefRefusjonsgruppe() {
        if (refRefusjonsgruppe == null) {
            refRefusjonsgruppe = new ArrayList<JAXBElement<Object>>();
        }
        return this.refRefusjonsgruppe;
    }

    /**
     * Gets the value of the gyldigFraDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGyldigFraDato() {
        return gyldigFraDato;
    }

    /**
     * Sets the value of the gyldigFraDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGyldigFraDato(XMLGregorianCalendar value) {
        this.gyldigFraDato = value;
    }

    /**
     * Gets the value of the forskrivesTilDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getForskrivesTilDato() {
        return forskrivesTilDato;
    }

    /**
     * Sets the value of the forskrivesTilDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setForskrivesTilDato(XMLGregorianCalendar value) {
        this.forskrivesTilDato = value;
    }

    /**
     * Gets the value of the utleveresTilDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUtleveresTilDato() {
        return utleveresTilDato;
    }

    /**
     * Sets the value of the utleveresTilDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUtleveresTilDato(XMLGregorianCalendar value) {
        this.utleveresTilDato = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<JAXBElement<Object>> theRefRefusjonsgruppe;
            theRefRefusjonsgruppe = (((this.refRefusjonsgruppe!= null)&&(!this.refRefusjonsgruppe.isEmpty()))?this.getRefRefusjonsgruppe():null);
            strategy.appendField(locator, this, "refRefusjonsgruppe", buffer, theRefRefusjonsgruppe);
        }
        {
            XMLGregorianCalendar theGyldigFraDato;
            theGyldigFraDato = this.getGyldigFraDato();
            strategy.appendField(locator, this, "gyldigFraDato", buffer, theGyldigFraDato);
        }
        {
            XMLGregorianCalendar theForskrivesTilDato;
            theForskrivesTilDato = this.getForskrivesTilDato();
            strategy.appendField(locator, this, "forskrivesTilDato", buffer, theForskrivesTilDato);
        }
        {
            XMLGregorianCalendar theUtleveresTilDato;
            theUtleveresTilDato = this.getUtleveresTilDato();
            strategy.appendField(locator, this, "utleveresTilDato", buffer, theUtleveresTilDato);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Refusjon)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Refusjon that = ((Refusjon) object);
        {
            List<JAXBElement<Object>> lhsRefRefusjonsgruppe;
            lhsRefRefusjonsgruppe = (((this.refRefusjonsgruppe!= null)&&(!this.refRefusjonsgruppe.isEmpty()))?this.getRefRefusjonsgruppe():null);
            List<JAXBElement<Object>> rhsRefRefusjonsgruppe;
            rhsRefRefusjonsgruppe = (((that.refRefusjonsgruppe!= null)&&(!that.refRefusjonsgruppe.isEmpty()))?that.getRefRefusjonsgruppe():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "refRefusjonsgruppe", lhsRefRefusjonsgruppe), LocatorUtils.property(thatLocator, "refRefusjonsgruppe", rhsRefRefusjonsgruppe), lhsRefRefusjonsgruppe, rhsRefRefusjonsgruppe)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsGyldigFraDato;
            lhsGyldigFraDato = this.getGyldigFraDato();
            XMLGregorianCalendar rhsGyldigFraDato;
            rhsGyldigFraDato = that.getGyldigFraDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "gyldigFraDato", lhsGyldigFraDato), LocatorUtils.property(thatLocator, "gyldigFraDato", rhsGyldigFraDato), lhsGyldigFraDato, rhsGyldigFraDato)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsForskrivesTilDato;
            lhsForskrivesTilDato = this.getForskrivesTilDato();
            XMLGregorianCalendar rhsForskrivesTilDato;
            rhsForskrivesTilDato = that.getForskrivesTilDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "forskrivesTilDato", lhsForskrivesTilDato), LocatorUtils.property(thatLocator, "forskrivesTilDato", rhsForskrivesTilDato), lhsForskrivesTilDato, rhsForskrivesTilDato)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsUtleveresTilDato;
            lhsUtleveresTilDato = this.getUtleveresTilDato();
            XMLGregorianCalendar rhsUtleveresTilDato;
            rhsUtleveresTilDato = that.getUtleveresTilDato();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "utleveresTilDato", lhsUtleveresTilDato), LocatorUtils.property(thatLocator, "utleveresTilDato", rhsUtleveresTilDato), lhsUtleveresTilDato, rhsUtleveresTilDato)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<JAXBElement<Object>> theRefRefusjonsgruppe;
            theRefRefusjonsgruppe = (((this.refRefusjonsgruppe!= null)&&(!this.refRefusjonsgruppe.isEmpty()))?this.getRefRefusjonsgruppe():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refRefusjonsgruppe", theRefRefusjonsgruppe), currentHashCode, theRefRefusjonsgruppe);
        }
        {
            XMLGregorianCalendar theGyldigFraDato;
            theGyldigFraDato = this.getGyldigFraDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "gyldigFraDato", theGyldigFraDato), currentHashCode, theGyldigFraDato);
        }
        {
            XMLGregorianCalendar theForskrivesTilDato;
            theForskrivesTilDato = this.getForskrivesTilDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "forskrivesTilDato", theForskrivesTilDato), currentHashCode, theForskrivesTilDato);
        }
        {
            XMLGregorianCalendar theUtleveresTilDato;
            theUtleveresTilDato = this.getUtleveresTilDato();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "utleveresTilDato", theUtleveresTilDato), currentHashCode, theUtleveresTilDato);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
