//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Teller" type="{http://www.kith.no/xmlstds}PQ"/&gt;
 *         &lt;element name="Nevner" type="{http://www.kith.no/xmlstds}PQ" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teller",
    "nevner"
})
@XmlRootElement(name = "Styrke")
public class Styrke
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "Teller", required = true)
    protected PQ teller;
    @XmlElement(name = "Nevner")
    protected PQ nevner;

    /**
     * Gets the value of the teller property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getTeller() {
        return teller;
    }

    /**
     * Sets the value of the teller property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setTeller(PQ value) {
        this.teller = value;
    }

    /**
     * Gets the value of the nevner property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getNevner() {
        return nevner;
    }

    /**
     * Sets the value of the nevner property.
     * 
     * @param value
     *     allowed object is
     *     {@link PQ }
     *     
     */
    public void setNevner(PQ value) {
        this.nevner = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            PQ theTeller;
            theTeller = this.getTeller();
            strategy.appendField(locator, this, "teller", buffer, theTeller);
        }
        {
            PQ theNevner;
            theNevner = this.getNevner();
            strategy.appendField(locator, this, "nevner", buffer, theNevner);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Styrke)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Styrke that = ((Styrke) object);
        {
            PQ lhsTeller;
            lhsTeller = this.getTeller();
            PQ rhsTeller;
            rhsTeller = that.getTeller();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "teller", lhsTeller), LocatorUtils.property(thatLocator, "teller", rhsTeller), lhsTeller, rhsTeller)) {
                return false;
            }
        }
        {
            PQ lhsNevner;
            lhsNevner = this.getNevner();
            PQ rhsNevner;
            rhsNevner = that.getNevner();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nevner", lhsNevner), LocatorUtils.property(thatLocator, "nevner", rhsNevner), lhsNevner, rhsNevner)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            PQ theTeller;
            theTeller = this.getTeller();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "teller", theTeller), currentHashCode, theTeller);
        }
        {
            PQ theNevner;
            theNevner = this.getNevner();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nevner", theNevner), currentHashCode, theNevner);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
