//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.19 at 09:29:28 PM CEST 
//


package no.uia.ehealth.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}ID"/&gt;
 *         &lt;element name="Navn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NavnEngelsk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RefVirkestoff" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01}Refusjon" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "navn",
    "navnEngelsk",
    "refVirkestoff",
    "refusjon"
})
@XmlRootElement(name = "Virkestoff")
public class Virkestoff
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlElement(name = "Navn", required = true)
    protected String navn;
    @XmlElement(name = "NavnEngelsk")
    protected String navnEngelsk;
    @XmlElementRef(name = "RefVirkestoff", namespace = "http://www.kith.no/xmlstds/eresept/forskrivning/2014-12-01", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Object>> refVirkestoff;
    @XmlElement(name = "Refusjon")
    protected List<Refusjon> refusjon;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the navn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavn() {
        return navn;
    }

    /**
     * Sets the value of the navn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavn(String value) {
        this.navn = value;
    }

    /**
     * Gets the value of the navnEngelsk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavnEngelsk() {
        return navnEngelsk;
    }

    /**
     * Sets the value of the navnEngelsk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavnEngelsk(String value) {
        this.navnEngelsk = value;
    }

    /**
     * Gets the value of the refVirkestoff property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refVirkestoff property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefVirkestoff().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getRefVirkestoff() {
        if (refVirkestoff == null) {
            refVirkestoff = new ArrayList<JAXBElement<Object>>();
        }
        return this.refVirkestoff;
    }

    /**
     * Gets the value of the refusjon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refusjon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefusjon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Refusjon }
     * 
     * 
     */
    public List<Refusjon> getRefusjon() {
        if (refusjon == null) {
            refusjon = new ArrayList<Refusjon>();
        }
        return this.refusjon;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theId;
            theId = this.getId();
            strategy.appendField(locator, this, "id", buffer, theId);
        }
        {
            String theNavn;
            theNavn = this.getNavn();
            strategy.appendField(locator, this, "navn", buffer, theNavn);
        }
        {
            String theNavnEngelsk;
            theNavnEngelsk = this.getNavnEngelsk();
            strategy.appendField(locator, this, "navnEngelsk", buffer, theNavnEngelsk);
        }
        {
            List<JAXBElement<Object>> theRefVirkestoff;
            theRefVirkestoff = (((this.refVirkestoff!= null)&&(!this.refVirkestoff.isEmpty()))?this.getRefVirkestoff():null);
            strategy.appendField(locator, this, "refVirkestoff", buffer, theRefVirkestoff);
        }
        {
            List<Refusjon> theRefusjon;
            theRefusjon = (((this.refusjon!= null)&&(!this.refusjon.isEmpty()))?this.getRefusjon():null);
            strategy.appendField(locator, this, "refusjon", buffer, theRefusjon);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Virkestoff)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Virkestoff that = ((Virkestoff) object);
        {
            String lhsId;
            lhsId = this.getId();
            String rhsId;
            rhsId = that.getId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                return false;
            }
        }
        {
            String lhsNavn;
            lhsNavn = this.getNavn();
            String rhsNavn;
            rhsNavn = that.getNavn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "navn", lhsNavn), LocatorUtils.property(thatLocator, "navn", rhsNavn), lhsNavn, rhsNavn)) {
                return false;
            }
        }
        {
            String lhsNavnEngelsk;
            lhsNavnEngelsk = this.getNavnEngelsk();
            String rhsNavnEngelsk;
            rhsNavnEngelsk = that.getNavnEngelsk();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "navnEngelsk", lhsNavnEngelsk), LocatorUtils.property(thatLocator, "navnEngelsk", rhsNavnEngelsk), lhsNavnEngelsk, rhsNavnEngelsk)) {
                return false;
            }
        }
        {
            List<JAXBElement<Object>> lhsRefVirkestoff;
            lhsRefVirkestoff = (((this.refVirkestoff!= null)&&(!this.refVirkestoff.isEmpty()))?this.getRefVirkestoff():null);
            List<JAXBElement<Object>> rhsRefVirkestoff;
            rhsRefVirkestoff = (((that.refVirkestoff!= null)&&(!that.refVirkestoff.isEmpty()))?that.getRefVirkestoff():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "refVirkestoff", lhsRefVirkestoff), LocatorUtils.property(thatLocator, "refVirkestoff", rhsRefVirkestoff), lhsRefVirkestoff, rhsRefVirkestoff)) {
                return false;
            }
        }
        {
            List<Refusjon> lhsRefusjon;
            lhsRefusjon = (((this.refusjon!= null)&&(!this.refusjon.isEmpty()))?this.getRefusjon():null);
            List<Refusjon> rhsRefusjon;
            rhsRefusjon = (((that.refusjon!= null)&&(!that.refusjon.isEmpty()))?that.getRefusjon():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "refusjon", lhsRefusjon), LocatorUtils.property(thatLocator, "refusjon", rhsRefusjon), lhsRefusjon, rhsRefusjon)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theId;
            theId = this.getId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
        }
        {
            String theNavn;
            theNavn = this.getNavn();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "navn", theNavn), currentHashCode, theNavn);
        }
        {
            String theNavnEngelsk;
            theNavnEngelsk = this.getNavnEngelsk();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "navnEngelsk", theNavnEngelsk), currentHashCode, theNavnEngelsk);
        }
        {
            List<JAXBElement<Object>> theRefVirkestoff;
            theRefVirkestoff = (((this.refVirkestoff!= null)&&(!this.refVirkestoff.isEmpty()))?this.getRefVirkestoff():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refVirkestoff", theRefVirkestoff), currentHashCode, theRefVirkestoff);
        }
        {
            List<Refusjon> theRefusjon;
            theRefusjon = (((this.refusjon!= null)&&(!this.refusjon.isEmpty()))?this.getRefusjon():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "refusjon", theRefusjon), currentHashCode, theRefusjon);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
